/*
 * Shortlink Service
 *
 * It is an URL shortener service - it can generate a short version of arbitrary user's URL.
 * Also user can get statistics for URL generated url (how much people followed the link).
 *
 * API version: 1.0.0
 * Contact: ptsypyshev@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Clicker struct {
	ID int64 `json:"id,omitempty"`

	UniqueCookie string `json:"uniqueCookie,omitempty"`

	IPAddress string `json:"ipAddress,omitempty"`

	Country string `json:"country,omitempty"`

	Status bool `json:"status,omitempty"`
}
