/*
 * Shortlink Service
 *
 * It is an URL shortener service - it can generate a short version of arbitrary user's URL.
 * Also user can get statistics for URL generated url (how much people followed the link).
 *
 * API version: 1.0.0
 * Contact: ptsypyshev@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LinksLinkIDBody struct {
	// Updated long link
	LongLink string `json:"longLink,omitempty"`
	// Updated status of the link
	Status string `json:"status,omitempty"`
}
