/*
 * Shortlink Service
 *
 * It is an URL shortener service - it can generate a short version of arbitrary user's URL.
 * Also user can get statistics for URL generated url (how much people followed the link).
 *
 * API version: 1.0.0
 * Contact: ptsypyshev@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/",
		Index,
	},

	Route{
		"AddLink",
		strings.ToUpper("Post"),
		"/links",
		AddLink,
	},

	Route{
		"DeleteLink",
		strings.ToUpper("Delete"),
		"/links/{linkId}",
		DeleteLink,
	},

	Route{
		"GetLinkByID",
		strings.ToUpper("Get"),
		"/links/{linkId}",
		GetLinkByID,
	},

	Route{
		"GetLinksByUsername",
		strings.ToUpper("Get"),
		"/users/{username}/links",
		GetLinksByUsername,
	},

	Route{
		"UpdateLink",
		strings.ToUpper("Put"),
		"/links",
		UpdateLink,
	},

	Route{
		"UpdateLinkWithForm",
		strings.ToUpper("Post"),
		"/links/{linkId}",
		UpdateLinkWithForm,
	},

	Route{
		"CreateUser",
		strings.ToUpper("Post"),
		"/users",
		CreateUser,
	},

	Route{
		"DeleteUser",
		strings.ToUpper("Delete"),
		"/users/{username}",
		DeleteUser,
	},

	Route{
		"GetUserByName",
		strings.ToUpper("Get"),
		"/users/{username}",
		GetUserByName,
	},

	Route{
		"LoginUser",
		strings.ToUpper("Post"),
		"/users/login",
		LoginUser,
	},

	Route{
		"LogoutUser",
		strings.ToUpper("Get"),
		"/users/logout",
		LogoutUser,
	},

	Route{
		"UpdateUser",
		strings.ToUpper("Put"),
		"/users/{username}",
		UpdateUser,
	},
}
