openapi: 3.0.3
info:
  title: Shortlink Service
  description: It is an URL shortener service - it can generate a short version of
    arbitrary user's URL. Also user can get statistics for URL generated url (how
    much people followed the link).
  contact:
    email: ptsypyshev@gmail.com
  version: 1.0.0
servers:
- url: https://localhost:8080/api/
tags:
- name: link
  description: "Operations about link (Long and short URLs, statistics, etc.)"
- name: user
  description: "Operations about user"
paths:
  /links:
    post:
        tags:
        - link
        summary: Create a new link with a new shotrlink
        operationId: addLink
        requestBody:
          description: Link object that needs to be added to the store
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Link'
          required: true
        responses:
          "200":
            description: "ok"
            content:
              application/json:
                example:
                  {"created": "5dg8s0"}
          "400":
            description: "bad request"
            content:
              application/json:
                example:
                  {"error": "bad request"}
          "500":
            description: "create link error"
            content:
              application/json:
                example:
                  {"error": "create link error"}
        security:
        - external_auth:
          - write:links
          - read:links
        x-codegen-request-body-name: body
    put:
      tags:
      - link
      summary: Update an existing link
      operationId: updateLink
      requestBody:
        description: Link object that needs to be updated in the store
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Link'
        required: true
      responses:
        "200":
            description: "ok"
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Link'
        "400":
          description: "bad request"
          content:
            application/json:
              example:
                {"error": "bad request"}
        "500":
          description: "update link error"
          content:
            application/json:
              example:
                {"error": "bad request"}
      security:
      - external_auth:
        - write:links
        - read:links
      x-codegen-request-body-name: body
  
  /links/{linkId}:
    get:
      tags:
      - link
      summary: Find link by ID
      description: Returns a single link
      operationId: getLinkById
      parameters:
      - name: linkId
        in: path
        description: ID of link to return
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Link'
        "400":
          description: "bad request"
          content:
            application/json:
              example:
                {"error": "bad request"}
        "404":
          description: Link not found
          content: {}
      
        "500":
          description: "update link error"
          content:
            application/json:
              example:
                {"error": "update link error"}
      security:  
      - api_key: []
    delete:
      tags:
      - link
      summary: Delete a link
      operationId: deleteLink
      parameters:
      - name: api_key
        in: header
        required: false
        style: simple
        explode: false
        schema:
          type: string
      - name: linkId
        in: path
        description: Link id to delete
        required: true
        style: simple
        explode: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Link'
        "400":
          description: "bad request"
          content:
            application/json:
              example:
                {"error": "bad request"}
        "404":
          description: Link not found
          content: {}
      
        "500":
          description: "delete link error"
          content:
            application/json:
              example:
                {"error": "delete link error"}
      security:
      - external_auth:
        - write:links
        - read:links
  /users:
    post:
      tags:
      - user
      summary: Create user
      description: This can only be done by the logged in user.
      operationId: createUser
      requestBody:
        description: Created user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: "ok"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: "bad request"
          content:
            application/json:
              example:
                {"error": "bad request"}
        "500":
          description: "create user error"
          content:
            application/json:
              example:
                {"error": "create user error"}
      security:
      - external_auth:
        - write:links
        - read:links
      x-codegen-request-body-name: body
    put:
      tags:
      - user
      summary: Updated user
      description: This can only be done by the logged in user.
      operationId: updateUser
      requestBody:
        description: Updated user object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        "200":
          description: "ok"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: "bad request"
          content:
            application/json:
              example:
                {"error": "bad request"}
        "500":
          description: "update user error"
          content:
            application/json:
              example:
                {"error": "update user error"}
      x-codegen-request-body-name: body
  /users/login:
    post:
      tags:
      - user
      summary: Logs user into the system
      operationId: loginUser
      parameters:
      - name: username
        in: query
        description: The user name for login
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: password
        in: query
        description: The password for login in clear text
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          headers:
            X-Rate-Limit:
              description: calls per hour allowed by the user
              style: simple
              explode: false
              schema:
                type: integer
                format: int32
            X-Expires-After:
              description: date in UTC when token expires
              style: simple
              explode: false
              schema:
                type: string
                format: date-time
          content:
            application/json:
              schema:
                type: string
                x-content-type: application/json
        "400":
          description: Invalid username/password supplied
          content: {}
  /users/logout:
    get:
      tags:
      - user
      summary: Logs out current logged in user session
      operationId: logoutUser
      responses:
        default:
          description: successful operation
          content: {}
  /users/{id}:
    get:
      tags:
      - user
      summary: Get user by id
      operationId: getUserByName
      parameters:
      - name: id
        in: path
        description: The id of user that needs to be fetched.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: "bad request"
          content:
            application/json:
              example:
                {"error": "bad request"}
        "500":
          description: "get user error"
          content:
            application/json:
              example:
                {"error": "get user error"}
    delete:
      tags:
      - user
      summary: Delete user
      description: This can only be done by the logged in user.
      operationId: deleteUser
      parameters:
      - name: id
        in: path
        description: The id of user that needs to be deleted.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        "400":
          description: "bad request"
          content:
            application/json:
              example:
                {"error": "bad request"}
        "500":
          description: "delete user error"
          content:
            application/json:
              example:
                {"error": "delete user error"}
  /users/{id}/links:
    get:
      tags:
      - link
      summary: Get links by username
      operationId: getLinksByUsername
      parameters:
      - name: id
        in: path
        description: The id of user which links should to be fetched.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Link'
                x-content-type: application/json
        "400":
          description: Invalid username supplied
          content: {}
        "404":
          description: User not found
          content: {}
components:
  schemas:
    Link:
      type: object
      properties:
        id:
          type: integer
          format: int64
        long_link:
          type: string
        click_counter:
          type: integer
          format: int64
        owner_id:
          type: integer
          format: int64
        is_active:
          type: boolean
          default: false
        short_link:
          type: string
      example:
        long_link: "https://ya.ru"
        id: 2
        status: true
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        password:
          type: string
          format: password
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        user_status:
          type: boolean
      example:
        id: 0
        username: "test"
        password: "pass"
        first_name: "Test"
        last_name: "User"
        email: "test@test.com"
        phone: "111"
        userStatus: true
  securitySchemes:
    external_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://localhost/oauth/dialog
          scopes:
            write:links: modify links in your account
            read:links: read your links
    api_key:
      type: apiKey
      name: api_key
      in: header
